apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ include "termbin.fullname" . }}
  name: {{ include "termbin.fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ include "termbin.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ include "termbin.fullname" . }}
    spec:
      containers:
        - env:
            - name: TBURL
              value: {{ .Values.ingress.host }}
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          name: termbin
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9999
              name: paste
              protocol: UDP
          resources: {}
          securityContext:
            runAsUser: 101
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: var-cache
            - mountPath: /var/run
              name: var-run
            - mountPath: /usr/share/nginx/html
              name: data
      securityContext: {}
      serviceAccountName: {{ include "termbin.fullname" . }}
      volumes:
        - emptyDir: {}
          name: var-run
        - emptyDir: {}
          name: var-cache
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "termbin.fullname" . }}
