apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: {{ include "termbin.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
