apiVersion: v1
kind: Service
metadata:
  name: {{ include "termbin.fullname" . }}
spec:
  ports:
    - name: paste
      port: 9999
      protocol: UDP
      targetPort: 9999
  selector:
    app: {{ include "termbin.fullname" . }}
  sessionAffinity: None
  type: LoadBalancer
