apiVersion: v1
kind: Service
metadata:
  name: {{ include "termbin.fullname" . }}-web
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ include "termbin.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
